version: "3"

services:
  zookeeper:
    image: jplock/zookeeper
    ports: 
      - "2181:2181"
  kafka:
    image: ches/kafka
    ports:
      - "7203:7203"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
      - KAFKA_ADVERTISED_PORT=9092
      - ZOOKEEPER_IP= 192.168.99.100
      - KAFKA_CREATE_TOPICS=transactions:2:1,blockchain:1:1
  consumer:
    build: .
    depends_on:
      - kafka
    ports:
    - "5000:5000" 
